version: "3.8"

services:
  deoxys:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: deoxys
    restart: unless-stopped
    ports:
      - "${RPC_PORT:-9944}:9944"
    volumes:
      - $HOME/deoxys:/var/lib/deoxys
    entrypoint: ["tini", "--"]
    command:
      [
        "/usr/local/bin/deoxys",
        "--base-path",
        "/var/lib/deoxys",
        "--network",
        "main",
        "--l1-endpoint",
        "${L1_ENDPOINT}",
      ]
    profiles:
      - mainnet

  deoxys-testnet:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: deoxys-testnet
    restart: unless-stopped
    ports:
      - "${RPC_PORT:-9944}:9944"
    volumes:
      - $HOME/deoxys-testnet:/var/lib/deoxys-testnet
    entrypoint: ["tini", "--"]
    command:
      [
        "/usr/local/bin/deoxys",
        "--base-path",
        "/var/lib/deoxys-testnet",
        "--network",
        "test",
        "--l1-endpoint",
        "https://eth-sepolia.g.alchemy.com/v2/WIUR5JUZXieEBkze6Xs3IOXWhsS840TX",
      ]
    profiles:
      - testnet
