services:
  madara:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: madara
    restart: unless-stopped
    ports:
      - "${RPC_PORT:-9944}:9944"
    volumes:
      - $HOME/madara:/var/lib/madara
    entrypoint: ["tini", "--"]
    command:
      [
        "/usr/local/bin/madara",
        "--base-path",
        "/var/lib/madara",
        "--network",
        "main",
        "--l1-endpoint",
        "${L1_ENDPOINT}",
      ]
    profiles:
      - mainnet

  madara-testnet:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: madara-testnet
    restart: unless-stopped
    ports:
      - "${RPC_PORT:-9944}:9944"
    volumes:
      - $HOME/madara-testnet:/var/lib/madara-testnet
    entrypoint: ["tini", "--"]
    command:
      [
        "/usr/local/bin/madara",
        "--base-path",
        "/var/lib/madara-testnet",
        "--network",
        "test",
        "--l1-endpoint",
        "${L1_ENDPOINT}",
      ]
    profiles:
      - testnet
