[package]
name = "madara_contracts"
version = "0.1.0"
edition = "2023_11"
cairo-version = "2.8.2"
scarb-version = "2.8.2"
authors = ["The Madara Committee <https://madara.build>"]
description = "Cairo contracts for boostrapping a madara network."

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.1" }
starknet = "2.8.2"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.27.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"
