---
name: Task - Linters Cargo

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cargo-lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.78
          components: rustfmt, clippy

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.8.2"

      - name: Setup build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libudev-dev protobuf-compiler libasound2-dev

      - name: Format and clippy
        run: |
          cargo fmt -- --check
          cargo clippy --workspace --no-deps -- -D warnings
          cargo clippy --workspace --tests --no-deps -- -D warnings
