name: Workflow - Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  build:
    name: Build Madara
    uses: ./.github/workflows/build.yml

  js_test:
    name: Run JS Tests
    uses: ./.github/workflows/starknet-js-test.yml
    needs: build
